### ISSUE TITLE
verify draft standard is being updated

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-environmental-data-retrieval#204]
The draft at http://docs.opengeospatial.org/DRAFTS/19-086.html seems to be out of date with what we have in master.  The desired workflow is that the draft should be updated when there is a commit/push.

**Comment by tomkralidis** [comment]
@ghobona is there anything we need to do from the EDR repo?  We will also remove the HTML and PDF (will do in a PR) that we being auto-generated to the repo proper.

**Comment by ghobona** [comment]
@tomkralidis 

The timestamp at http://docs.ogc.org/DRAFTS/ suggests that the document has been updated.

The "Last updated" footer created by asciidoctor does not appear to be based on the systems clock.

I have just tested this by making an edit on a local clone and then compiling the document. The edits were reflected but the "Last updated" footer did not change.

Noting that a new [PR](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/commit/69b787d3d49f400f4545cfb59b964323750c4ad2) has just been merged, if the changes in that PR do not appear in the draft at docs.ogc.org tomorrow at 09:00am EST then we can be sure that the document is not updating.

NOTE: I noticed that a commit from 2 days ago was also not showing in the compiled draft document. However, the commit might only have been merged into the master branch 2 hours ago. So let's check back tomorrow at  09:00am EST please.

Cc: @gbuehler

**Comment by tomkralidis** [comment]
Example commits from 2021-02-11 not evident on the draft:
- 2021-02-11: https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/commit/9be9465dcdc52a987363d2e5eac79a1747dacfe5
- 2021-02-11: https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/commit/017fe9117b2663d98c999900921c6360943b056a

**Comment by ghobona** [comment]
The Infrastructure Office is looking into it.

**Comment by chris-little** [comment]
@ghobona I think the issue is that the examples @tomkralidis provided were minor editorial changes, which were committed directly to the Master branch without a Pull Request, as per agreed SWG processes.
PR do seem to trigger a re-build of the document.

**Comment by ghobona** [comment]
@chris-little Shall I let the Infrastructure Office know that the issue has been resolved?

**Comment by chris-little** [comment]
@ghobona It is not yet resolved, in the sense that the infrastructure asciidoc batch file is only triggering on PRs. We would like it to be triggered by direct commits to Master too, but I do not know enough to do that.

**Comment by gbuehler** [comment]
Here are the errors from the build for the Candidate Standard:

- asciidoctor: ERROR: annex_requirements.adoc: line 16: include file not found: /candidate-standard/requirements/core/REQ_api-common.adoc
- asciidoctor: ERROR: abstract_tests/ATS_class_core.adoc: line 24: include file not found: /candidate-standard/abstract_tests/core/ATS_api-definition-op.adoc
- asciidoctor: ERROR: abstract_tests/ATS_class_core.adoc: line 30: include file not found: /candidate-standard/abstract_tests/core/ATS_conformance-op.adoc
- asciidoctor: ERROR: abstract_tests/ATS_class_queries.adoc: line 47: include file not found: /candidate-standard/abstract_tests/core/ATS_rc-op.adoc
- asciidoctor: ERROR: abstract_tests/ATS_class_queries.adoc: line 49: include file not found: /candidate-standard/abstract_tests/collections/ATS_rc-response.adoc

Error from the BP:
- asciidoctor: ERROR: clause_6_informative_text.adoc: line 12: include file not found: /best_practice/recommendations/core/REC_asynchronous-queries.adoc

**Comment by tomkralidis** [comment]
I think the asciidoctor issues are new and bound to recent changes per 25da8d65a89b10ac7ff02e3e1c53c70c21b5be57

**Comment by chris-little** [comment]
PR merged that addressess problem. @tomkralidis can build without error, but automatic overnight build still not happening

**Comment by chris-little** [comment]
Still not seeing overnight builds

**Comment by tomkralidis** [comment]
IMO it's critical path to address this issue.  For example, at the last member meeting, others mentioned the confusion that this is causing.

**Comment by tomkralidis** [comment]
Update EDR SWG: 2021-04-22: this issue has elevated priority given the above.

@ghobona @gbuehler what is the workflow/process which updates the draft at http://docs.opengeospatial.org/DRAFTS/19-086.html ?  Note that the document builds without error when we run the `.bat` files in the `candidate-standard` directory locally.  Let us know how we can help/test.

**Comment by chris-little** [comment]
@ogcscotts took an action to have a look

**Comment by ogcscotts** [comment]
@gbuehler I tested today and confirmed that the local batch executes correctly.

**Comment by ghobona** [comment]
It's best to wait until the metanorma version of the document has been moved into this repo, in 2 weeks time.

**Comment by chris-little** [comment]
@tomkralidis @m-burgoyne @dblodgett-usgs I propose to close this, as the standard is no longer Draft, but published final. We can start anoth issue if a new branch does not update.

**Comment by m-burgoyne** [comment]
@chris-little  I am happy with that suggestion

**Comment by tomkralidis** [comment]
Fair enough.  We may want to consider building the "master" branch as a rule to ensure the document build works as time goes on.  Of course this depends on whether we are working towards 1.x (stable branch) or 2.0 (master).

**Comment by chris-little** [comment]
As agreed at EDR API SWG #61, on 2021-09-13
